In [1]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv(r"D:\CampusX\Projects\EmailSpamDetector\data\raw\emails.csv")
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64
dtypes: int64(1), object(1)
memory usage: 89.6+ KB

In [8]:
df.columns

Index(['text', 'spam'], dtype='object')

In [10]:
df1 = df.copy()

In [ ]:
df1["num_characters"] = df['text'].apply(len)

In [11]:
df.text.apply(len)

0       1484
1        598
2        448
3        500
4        235
        ...
5723    1189
5724    1167
5725    2131
5726    1060
5727    2331
Name: text, Length: 5728, dtype: int64

In [13]:
df.duplicated().sum()

33

In [14]:
df.drop_duplicates()

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [19]:
import nltk
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sanja\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [21]:
import nltk
print(nltk.__version__)

3.10.0

In [22]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sanja\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [23]:
df.text.apply(lambda x: len(nltk.word_tokenize(x)))

0       325
1        90
2        88
3        99
4        53
       ...
5723    298
5724    245
5725    516
5726    277
5727    445
Name: text, Length: 5728, dtype: int64

In [25]:
df.text.apply(lambda x: len(nltk.sent_tokenize(x)))

0       11
1        1
2        4
3        5
4        9
        ..
5723     7
5724    28
5725    30
5726     6
5727    35
Name: text, Length: 5728, dtype: int64

In [29]:
type(df.text.apply(lambda x: x.lower()))

pandas.core.series.Series

In [ ]:
nltk.word_tokenize

0       Subject: naturally irresistible your corporate...
1       Subject: the stock trading gunslinger  fanny i...
2       Subject: unbelievable new homes made easy  im ...
3       Subject: 4 color printing special  request add...
4       Subject: do not have money , get software cds ...
                              ...
5723    Subject: re : research and development charges...
5724    Subject: re : receipts from visit  jim ,  than...
5725    Subject: re : enron case study update  wow ! a...
5726    Subject: re : interest  david ,  please , call...
5727    Subject: news : aurora 5 . 2 update  aurora ve...
Name: text, Length: 5728, dtype: object

In [51]:
from nltk.corpus import stopwords
stopwords.words("english")
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [66]:
def transfrom_text(text):
    # lower case
    text = text.lower()

    # convert into tokens
    text = nltk.word_tokenize(text)
    # print(text)

    # remove special characters
    text_list = []
    for i in text:
        if i.isalnum():
            text_list.append(i)
    
    # remove stopwords and punctuation mark( while punctuation marks has been removed by i.isalnum)
    temp = []
    for i in text_list:
        if i not in stopwords.words("english") and i not in string.punctuation:
            temp.append(i)



            
    return " ".join(temp)

In [69]:
import nltk
import string
from nltk.corpus import stopwords

# Load only once
STOP_WORDS = set(stopwords.words("english"))
PUNCTUATIONS = set(string.punctuation)

def transform_text(text):
    # Lowercase
    text = text.lower()

    # Tokenize
    tokens = nltk.word_tokenize(text)

    # Keep only alphanumeric tokens and remove stopwords
    filtered_tokens = [
        word for word in tokens
        if word.isalnum() and word not in STOP_WORDS
    ]

    return " ".join(filtered_tokens)

In [70]:
df["transform_text"] = df.text.apply(transfrom_text)
# transfrom_text("HI i am $$ you are great.?")
df

,text,spam,transform_text
0,Subject: naturally irresistible your corporate...,1,subject naturally irresistible corporate ident...
1,Subject: the stock trading gunslinger fanny i...,1,subject stock trading gunslinger fanny merrill...
2,Subject: unbelievable new homes made easy im ...,1,subject unbelievable new homes made easy im wa...
3,Subject: 4 color printing special request add...,1,subject 4 color printing special request addit...
4,"Subject: do not have money , get software cds ...",1,subject money get software cds software compat...
...,...,...,...
5723,Subject: re : research and development charges...,0,subject research development charges gpg forwa...
5724,"Subject: re : receipts from visit jim , than...",0,subject receipts visit jim thanks invitation v...
5725,Subject: re : enron case study update wow ! a...,0,subject enron case study update wow day super ...
5726,"Subject: re : interest david , please , call...",0,subject interest david please call shirley cre...
5727,Subject: news : aurora 5 . 2 update aurora ve...,0,subject news aurora 5 2 update aurora version ...

In [74]:
# df.head()
print(type(__name__))

<class 'str'>

In [72]:
df.to_csv("processes.csv")

In [ ]:
from sklearn.preprocessing import MinMaxScaler, SplineTransformer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, classification_report

In [76]:
df.head()

,text,spam,transform_text
0,Subject: naturally irresistible your corporate...,1,subject naturally irresistible corporate ident...
1,Subject: the stock trading gunslinger fanny i...,1,subject stock trading gunslinger fanny merrill...
2,Subject: unbelievable new homes made easy im ...,1,subject unbelievable new homes made easy im wa...
3,Subject: 4 color printing special request add...,1,subject 4 color printing special request addit...
4,"Subject: do not have money , get software cds ...",1,subject money get software cds software compat...

In [79]:
X = df.transform_text
cv = CountVectorizer()
X = cv.fit_transform(df.transform_text).toarray()
y = df.spam

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

gnb = GaussianNB()
bnb = BernoulliNB()
mnb = MultinomialNB()

In [86]:
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print("Result with Gaussian Nieve Bayes")
print(f"Accuracy {accuracy_score(y_test, y_pred)}")
print("Precision")
print(precision_score(y_test, y_pred))
print("Recall")
print(recall_score(y_test, y_pred))

Result with Gaussian Nieve Bayes
Accuracy 0.9581151832460733
Precision
0.9548872180451128
Recall
0.8758620689655172

In [87]:
bnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print("Result with Bernouli Nieve Bayes")
print(f"Accuracy {accuracy_score(y_test, y_pred)}")
print("Precision")
print(precision_score(y_test, y_pred))
print("Recall")
print(recall_score(y_test, y_pred))

Result with Bernouli Nieve Bayes
Accuracy 0.9581151832460733
Precision
0.9548872180451128
Recall
0.8758620689655172

In [88]:
mnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print("Result with Multinomial Nieve Bayes")
print(f"Accuracy {accuracy_score(y_test, y_pred)}")
print("Precision")
print(precision_score(y_test, y_pred))
print("Recall")
print(recall_score(y_test, y_pred))

Result with Multinomial Nieve Bayes
Accuracy 0.9581151832460733
Precision
0.9548872180451128
Recall
0.8758620689655172